version: "3"
networks:
  hami_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
services:
  hami_nginx:
    build:
      context: build/nginx
      dockerfile: Dockerfile
    container_name: hami_nginx
    depends_on:
      hami_app:
        condition: service_healthy
    restart: on-failure
    networks:
      hami_net:
        ipv4_address: 192.168.3.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/data/nginx/logs
      - ./nginx/certs:/data/nginx/certs
      - ./nginx/conf:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
  hami_app:
    build:
      args:
        - VERSION=0.0.1
      context: build/app
      dockerfile: Dockerfile
    container_name: hami_app
    depends_on:
      hami_mysql:
        condition: service_healthy
      hami_redis:
        condition: service_healthy
      hami_rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks:
      hami_net:
        ipv4_address: 192.168.3.11
    ports:
      - "8304:8304"
    volumes:
      - ./app:/root/hami
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8304/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    command:
      # 所有的配置都可在这里重写
      - --hami.cost-log=true
      - --hami.mode=test
      - --hami.email=wang3.top@gmail.com # 接受告警消息的邮箱
      - --hami.security.cookie.domain=hami.wang3.top # cookie写入的域名
      - --hami.security.secret=gfq3f3wgfp2rt23fwf # jwt密钥(随便打的)
      - --hami.security.cors.allowed-origins[0]=https://hami.wang3.top # cors allowedOrigin配置
      - --spring.datasource.url=jdbc:mysql://hami_mysql:3306/db_hami_community?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      - --spring.datasource.username=test
      - --spring.datasource.password=123456
      - --spring.data.redis.host=hami_redis
      - --spring.data.redis.password=123456
      - --spring.rabbitmq.host=hami_rabbitmq:wq
      - --spring.rabbitmq.username=root
      - --spring.rabbitmq.password=123456
      - --spring.rabbitmq.virtual-host=/
  hami_mysql:
    container_name: hami_mysql
    build:
      context: build/mysql
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.12
    ports:
      - "8300:3306"
    volumes:
      - ./db/conf/my.cnf:/etc/my.cnf
      - ./db/data:/var/lib/mysql
      - ./db/data:/var/lib/mysql-files
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=db_hami_community
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
  hami_redis:
    container_name: hami_redis
    build:
      context: build/redis
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.13
    ports:
      - "8301:6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    environment:
      - TZ=Asia/Shanghai
    command: ["redis-server", "/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 5s
      retries: 3
  hami_rabbitmq:
    container_name: hami_rabbitmq
    build:
      context: build/rabbitmq
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.14
    ports:
      - "8302:5672"
      - "8303:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
  hami_canal:
    container_name: hami_canal
    build:
      context: build/canal
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      hami_rabbitmq:
        condition: service_healthy
    networks:
      hami_net:
        ipv4_address: 192.168.3.15
    volumes:
      - ./canal/logs:/home/admin/canal-server/logs # 挂载日志
      #- ./canal/conf/instance.properties:/home/admin/canal-server/conf/example/instance.properties
      - ./canal/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
    environment:
      - TZ=Asia/Shanghai
      ## instance
      - canal.instance.master.address=hami_mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=123456
      ## 好像写在这里无效
#      - canal.serverMode=rabbitMQ
#      - canal.destinations=example
#      - canal.mq.flatMessage=true
#      - canal.mq.topic=/canal
#      - canal.mq.dynamicTopic=.*\\..*
#      - rabbitmq.host=hami_rabbitmq:5672
#      - rabbitmq.virtual.host=/
#      - rabbitmq.exchange=hami-canal-exchange
#      ## 用户名
#      - rabbitmq.username=root
#      ## 密码
#      - rabbitmq.password=123456
#      - rabbitmq.deliveryMode=topic
#      - rabbitmq.queue=hami-canal-queue
#      - rabbitmq.routingKey=/canal



