version: "3"
networks:
  hami_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
services:
  mysql:
    container_name: mysql
    build:
      context: build/mysql
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.11
    ports:
      - "8300:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/my.cnf
      - mysql_data:/var/lib/mysql
      - mysql_data:/var/lib/mysql-files
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=db_hami_community
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 5s
      retries: 3
  redis:
    container_name: redis
    build:
      context: build/redis
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.12
    ports:
      - "8301:6379"
    volumes:
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
      - redis_data:/data
    environment:
      - TZ=Asia/Shanghai
    command: ["redis-server", "/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
    labels:
      org.springframework.boot.ignore: true
  rabbitmq:
    container_name: rabbitmq
    build:
      context: build/rabbitmq
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.13
    ports:
      - "8302:5672"
      - "8303:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
  canal:
    container_name: canal
    build:
      context: build/canal
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - rabbitmq
    networks:
      hami_net:
        ipv4_address: 192.168.3.14
    volumes:
      - ./logs/canal:/home/admin/canal-server/logs # 挂载日志，主要是example里面的启动日志了
      - ./conf/canal/instance.properties:/home/admin/canal-server/conf/example/instance.properties
      - ./conf/canal/canal.properties:/home/admin/canal-server/conf/canal.properties
    environment:
      - TZ=Asia/Shanghai


