version: "3"
networks:
  hami_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.11
    ports:
      - "8300:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/my.cnf
      - mysql_data:/var/lib/mysql
      - mysql_data:/var/lib/mysql-files
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.12
    ports:
      - "8301:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - redis_data:/data
    environment:
      - TZ=Asia/Shanghai
    command: ["redis-server", "/etc/redis/redis.conf", "--appendonly yes"]
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    networks:
      hami_net:
        ipv4_address: 192.168.3.13
    ports:
      - "8302:5672"
      - "8303:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
  canal:
    container_name: canal
    build:
      context: ./canal
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - rabbitmq
    networks:
      hami_net:
        ipv4_address: 192.168.3.14
    volumes:
      - ./logs/canal:/home/admin/canal-server/logs # 挂载日志，主要是example 里面 的启动日志了
      - ./conf/canal/instance.properties:/home/admin/canal-server/conf/example/instance.properties
      - ./conf/canal/canal.properties:/home/admin/canal-server/conf/canal.properties
    environment:
      - TZ=Asia/Shanghai


